POST http://localhost:3009/api/user HTTP/1.1
content-type: application/json

{
  "firstName": "buba",
  "lastName": "camara",
  "phoneNumber":"12345689",
  "email":"buba@gmail.com",
  "password":"buba"
  
}



