PUT  http://localhost:3009/api/sale/6378c7da4a36143cce19dcbd
content-type: application/json 

{
  "description": "Apple",
  "qty": 2,
  "price": 200,
  "Total": 400,
  "userId": "6360fbe0069d35d3c5bb4895"
}
